### ISSUE TITLE
How to actually build this?

### ISSUE THREAD

**Issue by nonchip** [felixjones/gbaplusplus#26]
How would I go about to actually build anything with this? do you happen to have an example project, or a makefile/etc to show this?

I'm assuming I need something along `arm-noneabi-g++` as the compiler toolchain, but then I'd still be lacking linker scripts and something to generate the header/checksums/etc to make a "real" `.gba` file instead of just some ELF objects.

**Comment by nonchip** [comment]
or is that what your `gba-toolchain` is for? that looks like it links a BUNCH more different libraries, but I don't see this one actually being used there anywhere.

**Comment by felixjones** [comment]
It's a header-only library, so all you need to do is add the `gba/` folder to your project and then include it in your source code:
```c++
#include <gba/gba.hpp>
```

**Comment by nonchip** [comment]
> all you need to do is add the gba/ folder to your project and then include it in your source code

I got *that* part, my question was about how to *then* compile the source using your toolchain.

---
ah, ok, after some tinkering i managed to get it to do something:

* downloaded `gba-toolchain`
* added `gba-plusplus` submodule in my project

```cmake
cmake_minimum_required(VERSION 3.0)
project(gba_link_tester)
set(ROM_TITLE "Example")
set(ROM_GAME_CODE "CEGE")
set(ROM_MAKER_CODE "EG")
set(ROM_VERSION 100)

add_executable(gba_link_tester main.cpp)
set_target_properties(gba_link_tester PROPERTIES SUFFIX ".elf")

# add submodule include path, and set the correct CXX version
target_include_directories(gba_link_tester PRIVATE gba-plusplus/include)
set_property(TARGET gba_link_tester PROPERTY CXX_STANDARD 17)

gba_target_link_agb_abi(gba_link_tester)
gba_target_sources_instruction_set(gba_link_tester thumb)
gba_target_link_runtime(gba_link_tester rom)
gba_target_object_copy(gba_link_tester "gba_link_tester.elf" "gba_link_tester.gba")
gba_target_fix(gba_link_tester "gba_link_tester.gba" "${ROM_TITLE}" "${ROM_GAME_CODE}" "${ROM_MAKER_CODE}" ${ROM_VERSION})
```

this correctly made me a `.gba` file, which also does what i expect given my `main.cpp`, soo guess you might want to document this workflow somehow? or add "automated include" support for your own library to your own toolchain like you did with tonc etc ;)

**Comment by felixjones** [comment]
> > all you need to do is add the gba/ folder to your project and then include it in your source code
> 
> I got _that_ part, my question was about how to _then_ compile the source using your toolchain.

This would be a question for the [gba-toolchain](https://github.com/felixjones/gba-toolchain) project, then. Because gba-plusplus is header-only nothing needs compiling, you can use whatever compile tool you desire.

gba-toolchain has a convenience CMake function called `gba_target_link_gba_plusplus`, so you can do this:
```cmake
gba_target_link_gba_plusplus(gba_link_tester)
```
And the headers will automatically be available as `#include <gba/gba.hpp>`

For stability, gba-toolchain uses a snapshot of gba-plusplus, so if you want the latest then I recommend cloning this project manually as you have done.
